#!/usr/bin/env bash
# Generates a real, self-signed CA plus a broker keystore/truststore
# for WP-18 (security) -- idempotent, skips if already present.
#
# LOCAL-DEVELOPMENT-ONLY shortcut, explicitly: a real production
# deployment gets its broker certificate from an actual internal or
# public CA (or a cert-management system like Vault/cert-manager), not
# a throwaway self-signed CA generated by a shell script and committed
# nowhere -- see the lab README's "Production considerations."
#
# Runs openssl and keytool INSIDE the pinned apache/kafka:4.3.1 image
# (both confirmed present there) rather than depending on the host
# having a compatible version of either installed.
set -euo pipefail
# Prevents Git-Bash-on-Windows from rewriting the container-side half
# of the -v host:/certs mount spec below into a bogus Windows path.
export MSYS_NO_PATHCONV=1

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# A real finding building this script: with MSYS_NO_PATHCONV=1 (needed
# above), the HOST side of -v also stops being auto-translated -- a
# plain /d/Kafka/... POSIX-style path then gets silently misinterpreted
# by Docker Desktop, so files land somewhere OTHER than this real host
# directory (confirmed the hard way: `keytool -list` against a FRESH
# `docker run -v "$(pwd):/certs"` could read the generated files back,
# but a plain host `ls` in this exact directory showed nothing -- two
# different mount resolutions of the "same" POSIX path). `cygpath -w`
# gives the real, explicit Windows path Docker Desktop expects instead.
if command -v cygpath >/dev/null 2>&1; then
    DIR_FOR_DOCKER="$(cygpath -w "$DIR")"
else
    DIR_FOR_DOCKER="$DIR"
fi
PASSWORD="lab-security-changeit"
BROKER_HOSTNAME="security-broker"

if [ -f "$DIR/broker.keystore.p12" ] && [ -f "$DIR/truststore.p12" ]; then
    echo "Certs already present in $DIR, skipping generation."
    exit 0
fi

docker run --rm --user root -v "$DIR_FOR_DOCKER:/certs" --entrypoint bash apache/kafka:4.3.1 -c "
set -euo pipefail
cd /certs

# 1. A real, self-signed CA -- the root of trust every other cert here
#    chains to.
openssl req -new -x509 -keyout ca.key -out ca.crt -days 3650 \
    -subj '/CN=kafka-security-lab-ca/OU=lab/O=kafka-principal-engineer-lab' \
    -passout pass:'$PASSWORD'

# 2. The broker's own keystore (PKCS12) with a real key pair, CN
#    matching the broker's own hostname -- TLS hostname verification
#    checks this. A real finding building this lab: hostname
#    verification checks the SAN (Subject Alternative Name) extension,
#    not just the CN, in modern TLS -- a cert with ONLY
#    CN=security-broker failed real handshakes from a client connecting
#    via 'localhost' (the published host port), with 'SSL handshake
#    failed' the only symptom. The SAN below covers both the
#    docker-network hostname AND localhost/127.0.0.1, matching every
#    way this lab's own clients (in-network and host-side) actually
#    connect.
SAN='dns:security-broker,dns:localhost,ip:127.0.0.1'
keytool -genkeypair -alias broker -keyalg RSA -keysize 2048 -validity 3650 \
    -keystore broker.keystore.p12 -storetype PKCS12 \
    -dname 'CN=$BROKER_HOSTNAME,OU=lab,O=kafka-principal-engineer-lab' \
    -ext \"SAN=\$SAN\" \
    -storepass '$PASSWORD' -keypass '$PASSWORD'

# 3. A real certificate signing request from that keystore -- the SAN
#    extension must be requested again here; keytool does not carry it
#    over from step 2 automatically.
keytool -certreq -alias broker -keystore broker.keystore.p12 \
    -ext \"SAN=\$SAN\" \
    -storepass '$PASSWORD' -file broker.csr

# 4. The CA signs the broker's CSR for real -- this is the step that
#    makes the broker cert trustworthy to anyone who trusts the CA.
#    -extfile is required for the SAN to survive signing -- openssl's
#    x509 -req does NOT copy extensions from the CSR by default.
printf 'subjectAltName=DNS:security-broker,DNS:localhost,IP:127.0.0.1\n' > broker-san.ext
openssl x509 -req -CA ca.crt -CAkey ca.key -in broker.csr -out broker.crt \
    -days 3650 -CAcreateserial -passin pass:'$PASSWORD' -extfile broker-san.ext

# 5. The broker's keystore needs BOTH the CA cert (as a trusted anchor)
#    and its own signed cert (replacing the self-signed placeholder
#    keytool generated in step 2) to present a real, verifiable chain.
keytool -importcert -alias ca -keystore broker.keystore.p12 \
    -storepass '$PASSWORD' -file ca.crt -noprompt
keytool -importcert -alias broker -keystore broker.keystore.p12 \
    -storepass '$PASSWORD' -file broker.crt -noprompt

# 6. A truststore containing ONLY the CA cert -- what clients (and, in
#    a real mTLS setup, the broker itself) use to verify a presented
#    certificate chains back to a trusted root.
keytool -importcert -alias ca -keystore truststore.p12 -storetype PKCS12 \
    -storepass '$PASSWORD' -file ca.crt -noprompt

# World-readable -- the broker container (running as its own,
# different non-root user, appuser/1000) needs to read these files
# back from the same bind-mounted directory.
chmod 644 /certs/*.p12 /certs/*.crt /certs/*.key
"

echo "$PASSWORD" > "$DIR/store-password.txt"
echo "Generated broker.keystore.p12 and truststore.p12 in $DIR"
echo "Store/key password (local dev only, see store-password.txt): $PASSWORD"
