#!/usr/bin/env bash
# Prints the UI/API logins on request. They are generated by setup.sh and kept only in the
# `event-console-auth` Secret; they are not written anywhere else, so this is the one place to get them.
#
#   ./credentials.sh            # viewer (read-only) and operator (publish, requeue, clear)
set -euo pipefail
cd "$(dirname "$0")"
source ../_lib/common.sh

require_cluster
get() { kubectl -n event-console get secret event-console-auth -o "jsonpath={.data.$1}" | base64 -d; }
echo "Event Console logins (http://localhost:8089):"
echo "  viewer    $(get VIEWER_PASSWORD)    read only"
echo "  operator  $(get OPERATOR_PASSWORD)    read, publish, requeue, clear"
